version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15.4
    ports:
      - "5432:5432"  # Adjust the port as needed
    environment:
      POSTGRES_DB: dinner_db
      POSTGRES_USER: dinner_user
      POSTGRES_PASSWORD: secret_password


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm start
