version: '3'
services:
  db:
    image: postgres:15.4
    container_name: db
    ports:
      - "5432:5432"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
    - pg_data:/var/lib/postgresql/data

  backend:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      -  DB_NAME=${DB_NAME}
      -  DB_USER=${DB_USER}
      -  DB_PASS=${DB_PASS}
      -  DB_HOST=${DB_HOST}
      -  DB_PORT=${DB_PORT}
      -  INSTANCE_CONNECTION_NAME=${INSTANCE_CONNECTION_NAME}
    depends_on:
      - db

  frontend:
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm start

volumes:
  pg_data: