version: '3'
services:
  db:
    image: postgres:15.4
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dinner_db
      POSTGRES_USER: dinner_user
      POSTGRES_PASSWORD: secret_password
    volumes:
    - pg_data:/var/lib/postgresql/data

  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - db

  frontend:
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm start

volumes:
  pg_data: