name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Authenticate with Docker
        run: gcloud auth configure-docker

      - name: Build and push Docker images for Frontend
        working-directory: .
        run: |
          docker build -t eu.gcr.io/dinner-app-397715/dinnerproject-frontend ./frontend
          docker push eu.gcr.io/dinner-app-397715/dinnerproject-frontend

      - name: Build and push Docker images for Backend
        working-directory: .
        run: |
          docker build -t eu.gcr.io/dinner-app-397715/dinnerproject-backend ./backend
          docker push eu.gcr.io/dinner-app-397715/dinnerproject-backend

      - name: Deploy Cloud Run services
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'hello-cloud-run'
          image: 'eu.gcr.io/dinner-app-397715/dinnerproject-frontend'
        run: |
          gcloud run deploy dinner-frontend \
            --max-instances=1 \
            --min-instances=0 \
            --image eu.gcr.io/dinner-app-397715/dinnerproject-frontend \
            --region europe-north1 \
            --platform managed \
            --cpu=1 \
            --allow-unauthenticated

          gcloud run deploy dinner-backend \
            --max-instances=1 \
            --min-instances=0 \
            --image eu.gcr.io/dinner-app-397715/dinnerproject-backend \
            --region europe-north1 \
            --platform managed \
            --add-cloudsql-instances=[dinner-app-db]
            --allow-unauthenticated \
            --cpu=1 \
            --update-env-vars=[POSTGRES_USER=${{ secrets.POSTGRES_USER }},POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }},POSTGRES_DB=${{ secrets.POSTGRES_DB }}]
