name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Authenticate with Docker
        run: gcloud auth configure-docker

      - name: Build and push Docker images for Frontend
        working-directory: ./frontend
        run: |
          docker build -t eu.gcr.io/dinner-app-397715/dinnerproject-frontend .
          docker push eu.gcr.io/dinner-app-397715/dinnerproject-frontend

      - name: Build and push Docker images for Backend
        working-directory: ./backend
        run: |
          docker build -t eu.gcr.io/dinner-app-397715/dinnerproject-backend .
          docker push eu.gcr.io/dinner-app-397715/dinnerproject-backend

      - name: Deploy Cloud Run services
        run: |
          gcloud run deploy dinner-frontend \
            --image eu.gcr.io/dinner-app-397715/dinnerproject-frontend \
            --region europe-north1 \
            --platform managed \
            --allow-unauthenticated

          gcloud run deploy dinner-backend \
            --image eu.gcr.io/dinner-app-397715/dinnerproject-backend \
            --region europe-north1 \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars=POSTGRES_USER=${{ secrets.POSTGRES_USER }},POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }},POSTGRES_DB=${{ secrets.POSTGRES_DB }}
